version: '3.4'

services:
  app:
    image: modelingevolution/rocket-welder-sdk:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 8g
    shm_size: 4g
    ports:
      - 8080:80
      - 7000:7000
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "10"
    environment:
      - CameraAutostart=true
      - IsStreamingAutoStarted=true
      - CameraResolution="1920x1080"
      - DisableNetworkManager=true
      - Connections=""
    volumes:
      - "./data-storage:/app/wwwroot/videos"
    depends_on:
      - eventstore.db

  eventstore.db:
    image: eventstore/eventstore:lts
    environment:
      - EVENTSTORE_PROJECTION_COMPILATION_TIMEOUT=2500
      - EVENTSTORE_CLUSTER_SIZE=1
      - EVENTSTORE_RUN_PROJECTIONS=All
      - EVENTSTORE_START_STANDARD_PROJECTIONS=true
      - EVENTSTORE_EXT_TCP_PORT=1113
      - EVENTSTORE_HTTP_PORT=2113
      - EVENTSTORE_INSECURE=true
      - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
      - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --insecure http://eventstore.db:2113/health/live || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 24
    logging:
      driver: "json-file"
      options:
        max-size: "25m"
        max-file: "10"
    volumes:
      - type: volume
        source: eventstore-volume-data
        target: /var/lib/eventstore
      - type: volume
        source: eventstore-volume-logs
        target: /var/log/eventstore

volumes:
  eventstore-volume-data:
  eventstore-volume-logs:
